# PARENT can be specified when building with --build-arg PARENT=...
ARG PARENT=includeos/includeos-common:v0.12.0-rc.2.0
FROM $PARENT

VOLUME /service
WORKDIR /service

CMD cd build && \
  cp $(find ~/IncludeOS_install -name chainloader) /service/build/chainloader && \
  cmake .. && \
  make
