FROM includeos/includeos-common:0.10.0.1

VOLUME /service/build
WORKDIR /service/build

ENTRYPOINT ["qemu-system-i386", "-nographic", "-smp", "1", "-m", "128", "-net", "nic,model=virtio", "-net", "user", "-kernel"]
