# PARENT can be specified when building with --build-arg PARENT=...
ARG PARENT=includeos/includeos-common:v0.12.0-rc.1
FROM $PARENT

VOLUME /service
WORKDIR /service

CMD cd build && \
  export INCLUDEOS_PREFIX=/home/ubuntu/IncludeOS_install && \
  export CC=clang-3.8 && \
  export CXX=clang++-3.8 && \
  cmake .. && \
  make
