FROM includeos/includeos-common:v0.11.0-rc.2

VOLUME /public
WORKDIR /home/ubuntu/IncludeOS/examples/acorn

CMD mkdir build && cd build && \
  export INCLUDEOS_PREFIX=/home/ubuntu/IncludeOS_install && \
  export CC=clang-3.8 && \
  export CXX=clang++-3.8 && \
  rm -rf /home/ubuntu/IncludeOS/examples/acorn/disk1/public/* && \
  cp -a -v /public/. /home/ubuntu/IncludeOS/examples/acorn/disk1/public && \
  cmake .. && \
  make && \
  cp acorn /public
