FROM includeos/includeos-common:0.10.0.1

USER root

RUN apt-get update && apt-get -y install \
  dosfstools \
  grub-pc

USER ubuntu

VOLUME /service
WORKDIR /service

ENTRYPOINT ["/home/ubuntu/IncludeOS_install/includeos/scripts/grubify.sh"]
